### ISSUE TITLE
Last prediction seems to always be 0.

### ISSUE THREAD

**Issue by shell123** [cknd/pyESN#1]
Hello,

Thanks for the work I've been looking for an echo state network that is easy to use for awhile now. Anyway, whenever I use the predict function 0. is the last prediction value. You can see it in your Mackey glass example if you print prediction[-1]. It seems like it was a possible prediction value in that time series, but whenever I use another time series the last prediction continues to be 0. 

Am I wrong here? Can you replicate this problem? Thanks again, your echo state networks are giving me good results and are very easy to use.

**Comment by cknd** [comment]
thanks for noticing! should be fixed now.
